apiVersion: v1
kind: ReplicaSet
metadata:
  labels: 
    environment: production
    app: nginx
  name: nginx-demo
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          command: $print env
          image: nginx:mainline-bookworm
          ports:
            - containerPort: 80
              protocol: TCP    
      
             
          



